### ISSUE TITLE
Pasting a long enough list of subcriptions OOMs

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#1737]
### Hydrus version

613

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Ubuntu 24

### Bug description and reproduction

1. Create a few thousand subscription.
2. Paste a few thousand subscriptions at once.
3. Accept resurrection of subscriptions
4. Python will try to allocate a huge brick of memory and OOM. Processing the list in blocks will probably prevent this.  Work-around is to copy the list as bricks manually.

### Log output

```text
N/A
```

**Comment by hydrusnetwork** [comment]
Thank you for this report! I will see what I can do!

**Comment by hydrusnetwork** [comment]
Although now I think about it more, this _may_ be tricky, since I do keep subscription objects that you have changed in memory until the dialog closes. I basically defer sub load until they are actually edited in some way. So simply loading them in blocks won't save this OOM unless there is a temporary bump from the load. I'll have a think. Maybe I track total stuff loaded and stop the user if we hit 2GB of memory or something in a dialog instance.

**Comment by bbappserver** [comment]
>  since I do keep subscription objects that you have changed in memory until the dialog closes
@hydrusnetwork So the weird part is actually if I paste queries in multiple parts it doesn't OOM, that is if I take my extra long subs list and slice it in to thirds, and then do 3 separate pushes of the paste queries button it doesn't OOM.

This must means that a large temporary object exists between the pasting and updating the subs, but actually the subs being in memory until the dialog closes is a non-issue.  Other-wise we would also expect an OOM if I pasted my subs in multiple slices.

**Comment by hydrusnetwork** [comment]
I have fixed a very important massive cause of lag when doing some list operations, including this one in particular. I can now paste 800+ items into a sub and it only takes three seconds to figure it out This may have been the cause of this situation (so busy in an inefficient flurry of Qt updates that memory handling goes up the spout), or an aggravating factor. Please let me know how you get on in v625 onwards.

**Comment by bbappserver** [comment]
Adding a scroll view seems to have fixed it.  So the problem was the window got so long it just ate all of some important resource.  However the final of the 3 dialog boxes when pasting queries still does not use a scroll view like the first two and will cause the graphics subsystem to OOM.

**Comment by hydrusnetwork** [comment]
Thanks again. I have not had trouble with the final summary dialog--here is what I see:

<img width="494" height="1045" alt="Image" src="https://github.com/user-attachments/assets/5bbb72a3-9824-41a8-9996-5ce3e6e31d75" />

What does happen is the client then locks up after this, when it wants to actually add 5,000+ items to the list. I waited sixty seconds and no update, but the strange thing is when I went into debug mode, if I did one breakpoint interrupt, it finished after like 20 seconds, so it feels like something was getting into a jam somewhere. I wonder and suspect if some of the OOM issue here was me, say, generating a list of all the 5,000 selected indices a million times in some infinite C++-heavy update event loop, and python never having a gasp of time to itself to clear the garbage.

The main problem was some inefficient selection code. When you insert a bunch of stuff like this, my modern 'select-and-scroll-to' final action wants to select everything new, so thousands of things. For tomorrow's 639, I have greatly optimised the performance of all the 'hey, is exactly one thing selected?' type calls for very large selections, and now a sub with many thousands of items will handle very large selection changes about as fast as you can click (previously about a second for every selection change). Pasting the 5,000 test thing now comes back in about six seconds. Might be further optimisable.

Let me know how it works for you now please! I don't see any dialogs here that still do 'ok let's list every single item and become a 120,000-pixel tall text label' any more, but I might be missing something.

**Comment by bbappserver** [comment]
Upgraded pas V625 I must have been out by one.  No more OOMs works very well and even has the added bonus of making subscriptions dismiss way faster.  Thanks for the fix.
